# TODO(billy): this workflow has not been re-named from `acceptance` because
# Visual Snapshots compares against artifacts from the same workflow name (on main branch)
# We should rename this when we have a more finalized naming scheme.
#
# Also note that this name *MUST* match the filename because GHA
# only provides the workflow name (https://docs.github.com/en/free-pro-team@latest/actions/reference/environment-variables#default-environment-variables)
# and GH APIs only support querying by workflow *FILENAME* (https://developer.github.com/v3/actions/workflows/#get-a-workflow)
name: acceptance
on:
  push:
    branches:
      - master
      - releases/**
  pull_request:

jobs:
  visual-diff:
    if: always()
    # This guarantees that we will only schedule Visual Snapshots if all
    # workflows that generate artifacts succees
    name: triggers visual snapshot
    runs-on: ubuntu-20.04
    timeout-minutes: 20
    steps:
      - name: Diff snapshots
        id: visual-snapshots-diff
        uses: getsentry/action-visual-snapshot@armenzg/feat/report-status-branch
        with:
          api-token: ${{ secrets.VISUAL_SNAPSHOT_SECRET }}
          gcs-bucket: 'sentry-visual-snapshots'
          gcp-service-account-key: ${{ secrets.SNAPSHOT_GOOGLE_SERVICE_ACCOUNT_KEY }}
